version: '3.8'

services:
  identity-api:
    build:
      context: .
      dockerfile: Identity/Nauther.Identity.Api/Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=NautherIdentity;User=sa;Password=YourStrong!Password;TrustServerCertificate=True
      - ConnectionStrings__RedisConnectionString=redis:6379,password=YourStrong!RedisPassword
    depends_on:
      - db
      - redis
    networks:
      - nauther-network

  blazor-ui:
    build:
      context: .
      dockerfile: ui/Nauther.UI.Blazor/Dockerfile
    ports:
      - "5001:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - IdentityApi__BaseUrl=http://identity-api
    depends_on:
      - identity-api
    networks:
      - nauther-network

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong!Password
    ports:
      - "1433:1433"
    volumes:
      - sqldata:/var/opt/mssql
    networks:
      - nauther-network

  redis:
    image: redis:7.2-alpine
    command: redis-server --requirepass YourStrong!RedisPassword
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - nauther-network
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "YourStrong!RedisPassword", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

networks:
  nauther-network:
    driver: bridge

volumes:
  sqldata:
  redis_data: 