version: '3.8'

services:
  identity-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=NautherDb;User=sa;Password=Your_password123;TrustServerCertificate=True;
      - Redis__Configuration=redis:6379 # Assuming you're using Microsoft.Extensions.Caching.StackExchangeRedis
    depends_on:
      - db
      - redis
    networks:
      - app-network

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver-db
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    container_name: redis-cache
    command: ["redis-server", "--requirepass", "SuperSecret123"]
    ports:
      - "6379:6379"
    networks:
      - app-network

volumes:
  sqlserver-data:

networks:
  app-network:
