version: '3.8'

services:
  identity-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7777:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__SqlServerConnectionString=Server=db;Database=NautherDb;User=sa;Password=Your_password123;TrustServerCertificate=True;
      - ConnectionStrings__RedisConnectionString=redis:6379
      - ConnectionStrings__aied_mongodb=mongodb://mongo:27017

    depends_on:
      - db
      - redis
      - mongo
    networks:
      - app-network

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver-db
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql
    networks:
      - app-network
  mongo:
    image: mongo:4.4
    container_name: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network
  redis:
    image: redis:7-alpine
    container_name: redis-cache
    command: ["redis-server"]
    ports:
      - "6379:6379"
    networks:
      - app-network

volumes:
  sqlserver-data:
  mongo-data:

networks:
  app-network:
